### ISSUE TITLE
Bug NoteSeq: Chromatic scale 

### ISSUE THREAD

**Issue by Coirt** [jeremywen/JW-Modules#20]
V/Oct does not output C on the 2nd and 3rd octaves on NoteSeq when in Chromatic scale. It skips C and goes from B to B then C#.

![c missing from 2nd 3rd](https://user-images.githubusercontent.com/12150421/35072523-d416315e-fbdc-11e7-8933-65daf55f81d0.gif)

**Comment by jeremywen** [comment]
i need to fix this

**Comment by midiguru** [comment]
This bug is still there. I just ran into it tonight. It's less apparent in the scale quantized modes, because you do get the octave C's due to the clamping to the notes of the scale -- but if you'll listen close, you'll hear that there are, for example, three b-flats before the C in some modes because the cell that should be C is registering as a b-natural.

**Comment by jeremywen** [comment]
hopefully i have this fixed for v1

**Comment by Coirt** [comment]
Okay will test with latest build.

**Comment by Coirt** [comment]
Just checked there seems to be still present in v1

**Comment by Coirt** [comment]
Its seems when you select scale none it plays them no problem

**Comment by Coirt** [comment]
https://github.com/jeremywen/JW-Modules/commit/174e5438dafb12898ad6b8e1168b6524b0c1a69e#diff-87fa8a3a88586b8a19f4dc06cd5638b5L8

Ah I see, you have an array of 11 which is equal to 12 objects, an array of 12 is equal to 13 objects. Not sure if you use -1 to negate the array length in the code that might what causes it to skip if I had to guess.

This seems to fix the issue anyway: 
`int SCALE_CHROMATIC      [13]= {1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12};` 

I think it skips because there is no note 0 perhaps it is 1-12

**Comment by jeremywen** [comment]
working on it still...

**Comment by Coirt** [comment]
Seems good!
