### ISSUE TITLE
Polyphony in NoteSeq

### ISSUE THREAD

**Issue by dag2099** [jeremywen/JW-Modules#41]
I can't tell if I'm being dumb or NoteSeq is not working right. My expectation was that when I had three notes stacked in the grid that it would send three channels of notes out the poly v/oct jack. As it is it seems to send 16 channels of notes with most of them being set to zero. This means that if I send that into Bleak (for instance) it will produce 16 channels of notes rather than the 3 I want. Am I missing something? I know there's an "include inactive" switch but that doesn't seem to do very much.

(win 7)

**Comment by jeremywen** [comment]
Currently it uses 16 channels but would only send notes on the first 3 in your case.  In my next update you can select the number of polyphony channels so it doesn't create 16 instances of bleak and eat up CPU.  Sorry for the trouble.

Include inactive is basically a drum mode where each row is mapped to each channel.

**Comment by dag2099** [comment]
>  In my next update you can select the number of polyphony channels so it doesn't create 16 instances of bleak and eat up CPU.
Could it not just automatically send the same number of channels as there are notes selected in each step?
> Sorry for the trouble.
Don't worry. I think we all appreciate the work of module developers.

**Comment by jeremywen** [comment]
You could say the same for the midi in modules.  You have to select the number of channels ahead of time in those modules too.  I believe that it would not be a good idea to increase/decrease channels aka create and delete instances at a high right of speed.  This would probably cause cpu issues itself.  

Also a lot of people use it for random values and may only use a few channels.  This allows you to select the number of channels you want and save cpu instead of using possibly up to 16 channels for just other unused random values.
